#!/usr/bin/env bash
#Nginx must be running, and listening on port 80
#Bash script that runs and listen on port 80
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart
